from pathlib import Path

HTML = Path('admin-prenotazioni-barche.html')
UX = Path('boat-booking-admin-list-ux.js')


def replace_once(text, old, new, label):
    if old not in text:
        raise SystemExit(f'Anchor not found: {label}')
    return text.replace(old, new, 1)


html = HTML.read_text(encoding='utf-8')

css_anchor = "    .admin-slot-booking strong { color: #173e4b; }\n"
css_replacement = """    .admin-slot-booking strong { color: #173e4b; }\n\n    .admin-settings-group + .admin-settings-group {\n      margin-top: 28px;\n      padding-top: 26px;\n      border-top: 1px solid #e2e9eb;\n    }\n    .admin-settings-group h2 { margin-top: 0; }\n"""
html = replace_once(html, css_anchor, css_replacement, 'settings group styles')

old = '''          <details class="booking-card admin-collapsible">\n            <summary>Impostazioni prenotazioni</summary>\n            <div class="admin-collapsible__body">\n              <div class="admin-settings-card">\n                <div>\n                  <h2>Chiusura prenotazioni</h2>\n                  <p class="booking-card__intro">Dopo questo termine gli utenti potranno consultare la prenotazione tramite codice, ma non crearla o modificarla. L’area admin resta operativa.</p>\n                  <div class="cutoff-state" data-cutoff-state></div>\n                </div>\n                <form class="cutoff-form" data-cutoff-form>\n                  <div class="booking-field">\n                    <label for="cutoffLocal">Data e ora di chiusura</label>\n                    <input id="cutoffLocal" name="cutoffLocal" type="datetime-local">\n                    <span class="booking-help">Orario di Pesaro (Europe/Rome).</span>\n                  </div>\n                  <div class="booking-actions">\n                    <button class="admin-button admin-button--primary" type="submit">Salva termine</button>\n                    <button class="admin-button" type="button" data-clear-cutoff>Rimuovi scadenza</button>\n                  </div>\n                </form>\n              </div>\n            </div>\n          </details>\n\n          <details class="booking-card admin-collapsible">\n            <summary>Anagrafica barche</summary>\n            <div class="admin-collapsible__body">\n              <p class="booking-card__intro">Il numero identifica la barca fisica e, una volta inserito, non può essere modificato. Le disponibilità degli slot sono calcolate automaticamente sulle barche attive.</p>\n\n              <form class="boat-registry-form" data-boat-form>\n                <div class="booking-field">\n                  <label for="boatNumber">Numero barca</label>\n                  <input id="boatNumber" name="number" maxlength="40" placeholder="Es. 101" required>\n                </div>\n                <div class="booking-field">\n                  <label for="boatBuilder">Cantiere</label>\n                  <select id="boatBuilder" name="builder" required><option value="">Scegli</option><option>LOVA</option><option>Swift</option></select>\n                </div>\n                <div class="booking-field">\n                  <label for="boatType">Tipo</label>\n                  <select id="boatType" name="boatType" required><option value="">Scegli</option><option>C1x</option><option>C2x</option><option>C4x+</option></select>\n                </div>\n                <button class="admin-button admin-button--primary" type="submit">Aggiungi barca</button>\n              </form>\n\n              <div data-boats-table></div>\n            </div>\n          </details>'''

new = '''          <details class="booking-card admin-collapsible">\n            <summary>Impostazioni</summary>\n            <div class="admin-collapsible__body">\n              <section class="admin-settings-group">\n                <div class="admin-settings-card">\n                  <div>\n                    <h2>Chiusura prenotazioni</h2>\n                    <p class="booking-card__intro">Dopo questo termine gli utenti potranno consultare la prenotazione tramite codice, ma non crearla o modificarla. L’area admin resta operativa.</p>\n                    <div class="cutoff-state" data-cutoff-state></div>\n                  </div>\n                  <form class="cutoff-form" data-cutoff-form>\n                    <div class="booking-field">\n                      <label for="cutoffLocal">Data e ora di chiusura</label>\n                      <input id="cutoffLocal" name="cutoffLocal" type="datetime-local">\n                      <span class="booking-help">Orario di Pesaro (Europe/Rome).</span>\n                    </div>\n                    <div class="booking-actions">\n                      <button class="admin-button admin-button--primary" type="submit">Salva termine</button>\n                      <button class="admin-button" type="button" data-clear-cutoff>Rimuovi scadenza</button>\n                    </div>\n                  </form>\n                </div>\n              </section>\n\n              <section class="admin-settings-group">\n                <h2>Anagrafica barche</h2>\n                <p class="booking-card__intro">Il numero identifica la barca fisica e, una volta inserito, non può essere modificato. Le disponibilità degli slot sono calcolate automaticamente sulle barche attive.</p>\n\n                <form class="boat-registry-form" data-boat-form>\n                  <div class="booking-field">\n                    <label for="boatNumber">Numero barca</label>\n                    <input id="boatNumber" name="number" maxlength="40" placeholder="Es. 101" required>\n                  </div>\n                  <div class="booking-field">\n                    <label for="boatBuilder">Cantiere</label>\n                    <select id="boatBuilder" name="builder" required><option value="">Scegli</option><option>LOVA</option><option>Swift</option></select>\n                  </div>\n                  <div class="booking-field">\n                    <label for="boatType">Tipo</label>\n                    <select id="boatType" name="boatType" required><option value="">Scegli</option><option>C1x</option><option>C2x</option><option>C4x+</option></select>\n                  </div>\n                  <button class="admin-button admin-button--primary" type="submit">Aggiungi barca</button>\n                </form>\n\n                <div data-boats-table></div>\n              </section>\n            </div>\n          </details>'''

html = replace_once(html, old, new, 'merge settings sections')
HTML.write_text(html, encoding='utf-8')

ux = UX.read_text(encoding='utf-8')
old_ux = '''      const slotSection = sections.find((details) => details.querySelector(':scope > summary')?.textContent.trim() === 'Slot orari');\n      const settingsSection = sections.find((details) => details.querySelector(':scope > summary')?.textContent.trim() === 'Impostazioni prenotazioni');\n      const boatsSection = sections.find((details) => details.querySelector(':scope > summary')?.textContent.trim() === 'Anagrafica barche');\n\n      if (slotSection) slotSection.hidden = true;\n      if (settingsSection && boatsSection && settingsSection.nextElementSibling !== boatsSection) {\n        secondary.insertBefore(settingsSection, boatsSection);\n      }\n'''
new_ux = '''      const slotSection = sections.find((details) => details.querySelector(':scope > summary')?.textContent.trim() === 'Slot orari');\n      if (slotSection) slotSection.hidden = true;\n'''
ux = replace_once(ux, old_ux, new_ux, 'remove obsolete settings ordering')
UX.write_text(ux, encoding='utf-8')
